version: "3"

services:
  influxdb:
    image: influxdb:2.7.11
    platform: linux/amd64
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb2
      - ./docker/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=switchbot

  grafana:
    image: grafana/grafana-oss:11.3.4
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb

  webserver:
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./docker/webserver:/app
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    depends_on:
      - influxdb
